# Generated by Django 4.2.27 on 2025-12-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
