# Generated by Django 4.2.28 on 2026-02-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_dependent_linked_user_medicalreport_dependent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
    ]
